WIP: Landing Page with Preview API Demonstration
torchbox/careers pull request #10
Opened 2021-12-07 11:50 UTC by jhancock532

This branch tests some core API functionality; pulling data from Contentful, and enabling Contentful's preview mode by clicking "Open Preview" in the Contentful editor.

2021-12-14 16:40 UTC, Morsey187 requested changes

2022-01-20 16:31 UTC, jhancock532 commented on lib/api.ts
> +        `https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}`,
Good idea, set this up :)

2022-01-20 16:33 UTC, jhancock532 commented on lib/api.ts
> +async function fetchGraphQL(query = "", preview = false) {
I'm currently using Contentful's Graphql explorer, but we could definitely add a ticket for this

2022-01-26 16:13 UTC, jhancock532 commented
I've added an early draft of the RichText renderer to this branch as it relies on data from Contentful to render elements. 

I'm not sure about my implementation as there wasn't any documentation about how to make this using TypeScript - be especially careful of the weird type requirements I encountered (I've commented these where appropriate)

I've decided on three color themes for this component to render, based on the existing figma designs. I've used styled components for this, it looks a bit awkward at the moment - there's potential for some refactoring here.

2022-01-26 16:21 UTC, jhancock532 commented on components/RichText.tsx
> +};
Unnecessary testing data, to be deleted (or converted into a Jest test)

2022-01-26 16:22 UTC, jhancock532 commented on components/RichText.tsx
> +        <div className={styles.container}>
styles.container is unused, we might add style here when we integrate this component into the landing page

2022-01-26 16:24 UTC, jhancock532 commented on components/RichText.tsx
> +};
To be deleted or refactored (I avoided this solution initially as I would have to pass the `node` with an unknown type into the function - however, we could use this function and just pass the node with `: any` instead

2022-01-26 16:25 UTC, jhancock532 commented on components/RichText.tsx
> +type Theme = "LIGHT" | "DARK" | "INDIGO";
Light for the job post page, dark for the homepage, indigo for the homepage. This should be worth writing documentation about?

2022-01-26 16:25 UTC, jhancock532 commented on pages/index.tsx
> +    console.log("Test 1 ", JSON.stringify(landingPageContent.ctaDescription));
Used for testing, to be deleted.

2022-01-26 16:26 UTC, jhancock532 commented on styles/RichText.module.scss
> +    color: var(--color--grey);
Line-heights aren't responsive here - refactor the SCSS to include line heights that vary as the font size changes? @include font-size(s) should also include line height?

2022-01-26 16:29 UTC, jhancock532 commented on styles/RichText.module.scss
> +}
Refactor as `.paragraphIndigo, .paragraphDark, ... { ... }` for common rules. Or use a seperate `.paragraph` class instead & double up with `styles.paragraph` & `styles.paragraphIndigo`. Or use a more generic utility class based solution with scss?

2022-01-26 16:30 UTC, jhancock532 commented on styles/RichText.module.scss
> +}
Taken from designs, ideally refactored into `_variables.scss`

2022-01-28 11:20 UTC, Morsey187 approved these changes
Happy with this, perhaps we can seperate the graphql queires into their own strings to export and import them else where at a later point if that become nescassary.

2022-01-28 12:40 UTC, merged